# Generated by Django 4.1 on 2025-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_booking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Cancelled by Admin', 'Cancelled by Admin')], default='Pending', max_length=20),
        ),
    ]
