# Generated by Django 4.1 on 2025-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_booking_email_booking_name_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, default='Your Name', max_length=100, null=True),
        ),
    ]
