# Generated by Django 4.1 on 2025-10-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
