# Generated by Django 4.1 on 2025-11-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
