# Generated by Django 4.1 on 2025-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_booking_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
