# Generated by Django 4.1 on 2025-11-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_brand_slug_alter_brand_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
