# Generated by Django 4.1 on 2025-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_advance_paid',
            field=models.BooleanField(default=False),
        ),
    ]
