# Generated by Django 4.1 on 2025-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='Example: 2 hrs, 30 mins', max_length=50)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('detailing', 'Detailing'), ('repair', 'Repair'), ('customization', 'Customization'), ('premium', 'Premium')], max_length=50)),
            ],
        ),
    ]
