# Generated by Django 4.1 on 2025-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('book', 'Book Car'), ('rent', 'Rent Car'), ('test_drive', 'Test Drive'), ('service', 'Service Booking')], default='book', max_length=20),
        ),
    ]
