# Generated by Django 4.1 on 2025-11-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_service_date_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
