# Generated by Django 4.1 on 2025-11-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_service_price_max_service_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
