# Generated by Django 4.1 on 2025-11-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_service_process_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
