# Generated by Django 4.1 on 2025-11-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
    ]
