# Generated by Django 4.1 on 2025-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
