# Generated by Django 4.1 on 2025-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_review_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
