# Generated by Django 4.1 on 2025-11-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_booking_email_sent_booking_email_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_read',
        ),
    ]
