# Generated by Django 4.1 on 2025-11-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_review_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_read',
        ),
    ]
