# Generated by Django 4.1 on 2025-11-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_review_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
