# Generated by Django 4.1 on 2025-11-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_user_is_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('engine', 'Engine & Related'), ('transmission', 'Transmission & Drivetrain'), ('brakes', 'Brakes'), ('suspension', 'Suspension & Steering'), ('wheels', 'Wheels & Tires'), ('electrical', 'Electrical & Lighting'), ('cooling', 'Cooling & AC'), ('belts_hoses', 'Belts & Hoses'), ('misc', 'Miscellaneous')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
