# Generated by Django 4.1 on 2025-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_sparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
