# Generated by Django 4.1 on 2025-11-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_bookedsparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedsparepart',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookedsparepart',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
