# Generated by Django 4.1 on 2025-11-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_bookedsparepart_date_bookedsparepart_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedsparepart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookedsparepart',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='bookedsparepart',
            name='address',
            field=models.TextField(default='Address not provided'),
        ),
        migrations.AddField(
            model_name='bookedsparepart',
            name='car_name',
            field=models.CharField(default='Unknown Car', max_length=100),
        ),
        migrations.AddField(
            model_name='bookedsparepart',
            name='customer_name',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AddField(
            model_name='bookedsparepart',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
        ),
    ]
