# Generated by Django 4.1 on 2025-11-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_remove_bookedsparepart_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedsparepart',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='bookedsparepart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
