# Generated by Django 4.1 on 2025-11-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_rename_booked_at_bookedsparepart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
    ]
