# Generated by Django 4.1 on 2025-11-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_bookedsparepart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
