# Generated by Django 4.1 on 2025-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_bookedsparepart_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
