# Generated by Django 4.1 on 2025-11-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_bookedsparepart_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
