# Generated by Django 4.1 on 2025-11-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_bookedsparepart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
