# Generated by Django 4.1 on 2025-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_sparepart_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
