# Generated by Django 4.1 on 2025-11-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_bookedsparepart_deleted_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spare_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bookedsparepart'),
        ),
    ]
