# Generated by Django 4.1 on 2025-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_review_spare_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
