# Generated by Django 4.1 on 2025-11-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_booking_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
