# Generated by Django 4.1 on 2025-11-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_bookedsparepart_refund_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='payment_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
