# Generated by Django 4.1 on 2025-11-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_bookedsparepart_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedsparepart',
            name='payment_id',
        ),
    ]
