# Generated by Django 4.1 on 2025-11-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_remove_bookedsparepart_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
    ]
