# Generated by Django 4.1 on 2025-11-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_bookedsparepart_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
