# Generated by Django 4.1 on 2025-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_booking_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsparepart',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
