# Generated by Django 4.1 on 2025-12-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_newslettermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsparepart',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('delivered', 'Delivered'), ('Cancelled by User', 'Cancelled by User'), ('Refunded', 'Refunded')], default='booked', max_length=20),
        ),
    ]
