# Generated by Django 4.1 on 2025-12-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_alter_bookedsparepart_status'),
    ]

    operations = [
         migrations.AddField(
            model_name='sparepart',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
